version: '3'
services:
  server:
    build: .
    env_file: .env
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 9001:9001
    command: yarn start
    volumes:
      - ./server:/home/app/

  client:
    build: .
    env_file: .env
    restart: always
    ports:
      - 9002:9002
      - 9003:9003
    command: yarn start
    volumes:
      - ./client:/home/app/

  db:
    image: mongo
    restart: always
    user: 1000:1000
    volumes:
      - ./server/data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

  redis:
    image: redis:6.0.6-alpine
    restart: always
