version: '3'
services:
  app:
    build: .
    container_name: 2dmmo
    env_file: .env
    restart: always
    depends_on:
      - redis
    networks:
      - default
      - proxy
    ports:
      - 9001:9001
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.2dmmo.rule=Host(`2dmmo.strutcode.dev`)
      - traefik.http.routers.2dmmo.entrypoints=web
      - traefik.http.routers.2dmmo-secure.rule=Host(`2dmmo.strutcode.dev`)
      - traefik.http.routers.2dmmo-secure.entrypoints=websecure
      - traefik.http.routers.2dmmo-secure.tls.certresolver=leresolver

  redis:
    image: redis:6.0.6-alpine
    restart: always

networks:
  proxy:
    external: true
