version: '3'
services:
  app:
    build: .
    env_file: .env
    depends_on:
      - mongo
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/
      - /home/app/node_modules

  db:
    image: couchdb:3.1
    restart: always
