version: '3'
services:
  app:
    build: .
    container_name: 2dmmo
    env_file: .env
    tty: true
    restart: always
    depends_on:
      - db
    networks:
      - default
      - proxy
    ports:
      - 9001:9001
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.2dmmo.rule=Host(`2dmmo.strutcode.dev`)
      - traefik.http.routers.2dmmo.entrypoints=web
      - traefik.http.routers.2dmmo-secure.rule=Host(`2dmmo.strutcode.dev`)
      - traefik.http.routers.2dmmo-secure.entrypoints=websecure
      - traefik.http.routers.2dmmo-secure.tls.certresolver=leresolver

  db:
    image: couchdb:3.1
    restart: always
    environment:
      COUCHDB_USER: root
      COUCHDB_PASSWORD: test

networks:
  proxy:
    external: true
