version: '3'
services:
  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 9001:9001
    working_dir: /home/app/web
    command: yarn start
    volumes:
      - ./assets:/home/app/assets
      - ./web:/home/app/web
      - ./tsconfig.json:/home/app/tsconfig.json

  client:
    build: .
    restart: always
    ports:
      - 9002:9002
    working_dir: /home/app/client
    command: yarn start
    volumes:
      - ./client:/home/app/client
      - ./common:/home/app/common
      - ./tsconfig.json:/home/app/tsconfig.json

  server:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 9003:9003
    working_dir: /home/app/server
    command: yarn start
    volumes:
      - ./assets:/home/app/assets
      - ./server:/home/app/server
      - ./common:/home/app/common
      - ./tsconfig.json:/home/app/tsconfig.json

  editor:
    build: .
    restart: always
    ports:
      - 9004:9004
    working_dir: /home/app/editor
    command: yarn start
    volumes:
      - ./editor:/home/app/editor
      - ./common:/home/app/common
      - ./tsconfig.json:/home/app/tsconfig.json

  db:
    image: mongo
    restart: always
    user: 1000:1000
    volumes:
      - ./server/data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

  redis:
    image: redis:6.0.6-alpine
    restart: always
